# Generated by Django 5.0.4 on 2024-04-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='Employee',
        ),
    ]
